Repository raphaelalkamim/macroChallengeEvents, pull requests merged in 2022-10, with the labels that each got.

#103 corrigir problema do sign out
  macroChallengeApp/macroChallengeApp/Flows/Login/SignInWithAppleManager.swift
  macroChallengeApp/macroChallengeApp/Models/DataManager.swift
Labels: bug

#129 Fix/share code
  macroChallengeApp/macroChallengeApp/CoreData/Class/ActivityRepositoryClass.swift
  macroChallengeApp/macroChallengeApp/CoreData/Class/RoadmapRepositoryClass.swift
  macroChallengeApp/macroChallengeApp/CoreData/Class/UserRepositoryClass.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/Extensions/MyTripViewControllerExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/ViewController/MyTripViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/Explore/Explore/ViewController/PreviewRoadmapViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/Extension/NewActivityExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewCell/CategoryActivityCollectionViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewCell/CurrencyTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewCell/ValueTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/NewRoadmap/Controllers/ReviewTravelViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/Extensions/ProfileViewControllerExtension.swift
  macroChallengeApp/macroChallengeApp/Models/DataManager.swift
  macroChallengeApp/macroChallengeApp/Models/RoadmapDTO.swift
Labels: enhancement, fix

#132 Fix/bugs+improvements
  macroChallengeApp/macroChallengeApp.xcodeproj/project.pbxproj
  macroChallengeApp/macroChallengeApp/Controller/DataManager.swift
  macroChallengeApp/macroChallengeApp/Controller/NetworkMonitor.swift
  macroChallengeApp/macroChallengeApp/CoreData/Class/ActivityRepositoryClass.swift
  macroChallengeApp/macroChallengeApp/DesignSystem/Extensions/DesignSystem+UIImage.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/Extensions/MyTripViewControllerExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/UIViewCell/InfoTripCollectionViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/Explore/Explore/ViewController/RoadmapSearchTableViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/Extension/NewActivityExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewCell/ValueTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewController/NewActivityViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewRoadmap/UIViewCell/DatePickerTableViewCell.swift
Labels: bug, enhancement, fix

#135 Dev/fix features
  macroChallengeApp/macroChallengeApp.xcodeproj/project.pbxproj
  macroChallengeApp/macroChallengeApp/Coordinator/CurrentCoordinator.swift
  macroChallengeApp/macroChallengeApp/Coordinator/NewRoadmapCoordinator.swift
  macroChallengeApp/macroChallengeApp/Coordinator/ProfileCoordinator.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/Extensions/MyTripViewControllerExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/UIViewCell/ActivityTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/View/DetailView.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/View/MyTripView.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/ViewController/DetailViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/Current/ViewController/MyTripViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/Extension/NewActivityExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/View/NewActivityView.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewCell/DetailTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/NewActivity/ViewController/NewActivityViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewRoadmap/Controllers/DaysViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/NewRoadmap/View/DaysView.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/Extensions/ProfileViewController+ContextMenu.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/Extensions/ProfileViewControllerExtension.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/UIViewCell/NotificationPickerTableViewCell.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/View/EditProfileView.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/ViewController/EditProfileViewController.swift
  macroChallengeApp/macroChallengeApp/Flows/Profile/ViewController/ProfileViewController.swift
  macroChallengeApp/macroChallengeApp/Info.plist
  macroChallengeApp/macroChallengeApp/Localization/es-419.lproj/Localizable.strings
  macroChallengeApp/macroChallengeApp/Localization/pt-BR.lproj/Localizable.strings
  macroChallengeApp/macroChallengeApp/Models/Activity.swift
Labels: fix
